# The electron-builder config for the production site (https://shieldbattery.net)
# It should generally match the other build configs (except things that need to differ for this
# "region")
appId: net.shieldbattery.client
extraResources:
  - game/dist/**
files:
  - '!**/*.map'
  - '!build/**/*'
  - '!node_modules/**/*'
  - 'index.html'
  - 'assets/**/*'
  - 'dist/bundle.js'
  - 'dist/**/*.chunk.js'
  - from: 'dist/'
    to: './'
    filter:
      - 'index.js'
  - from: 'dist/native/'
    to: './native/'
    filter:
      - '**/*.js'
      - '**/*.node'
fileAssociations:
  ext: 'rep'
  name: 'Starcraft Broodwar Replay'
  description: 'Starcraft (Broodwar and Remastered) replay file'
  role: 'Viewer'
nsis:
  artifactName: '${productName}-setup-${version}.${ext}'
win:
  certificateSubjectName: Fast Expo Collective LLC
  signDlls: true
  rfc3161TimeStampServer: http://ts.ssl.com
  icon: icon.ico
  target: nsis

# These properties differ between configs
productName: ShieldBattery
publish:
  provider: spaces
  name: shieldbattery-cdn
  region: nyc3
  path: /app/
