# The electron-builder config for the production site (https://shieldbattery.net)
# It should generally match the other build configs (except things that need to differ for this
# "region")
appId: net.shieldbattery.client
extraResources:
  - game/dist/**
files:
  - '!**/*.map'
  - '!build/**/*'
  - '!node_modules/**/*'
  - 'index.html'
  - 'assets/**/*'
  - 'dist/bundle.js'
  - 'styles/**/*'
  - from: 'dist/'
    to: './'
    filter:
      - '**/bundle-main.js'
  - from: 'dist/'
    to: './native/'
    filter:
      - '**/process.js'
      - '**/*.node'
nsis:
  artifactName: '${productName}-setup-${version}.${ext}'
win:
  certificateSubjectName: Travis Collins
  icon: icon.ico
  target: nsis-web

# These properties differ between configs
productName: ShieldBattery
publish:
  provider: generic
  url: 'https://shieldbattery.net/published_artifacts/${os}'
