# The electron-builder config for the production site (https://shieldbattery.net)
# It should generally match the other build configs (except things that need to differ for this
# "region")
appId: net.shieldbattery.client
extraResources:
- game/dist/**
- "!game/dist/**/*.map"
files:
- "!**/*.map"
- "!build/**/*"
# Devtron and its deps bring in a *ton* of space hogging files, but aren't used in the packed app,
# so we manually strip them out. Bleh.
- "!node_modules/accessibility-developer-tools/**/*"
- "!node_modules/devtron/**/*"
- "!node_modules/highlight.js/**/*"
- "!node_modules/humanize-plus/**/*"
nsis:
  artifactName: "${productName}-setup-${version}.${ext}"
win:
  certificateSubjectName: Travis Collins
  icon: icon.ico
  target: nsis-web

# These properties differ between configs
productName: ShieldBattery
publish:
  provider: generic
  url: "https://shieldbattery.net/published_artifacts/${os}/"
