# The electron-builder config for the staging site (https://staging.shieldbattery.net)
# It should generally match the other build configs (except things that need to differ for this
# "region")
appId: net.shieldbattery.client.dev
extraResources:
  - game/dist/**
files:
  - '!**/*.map'
  - '!build/**/*'
  - '!node_modules/**/*'
  - 'index.html'
  - 'assets/**/*'
  - '!dist/index.js'
  - '!dist/preload.js'
  - '!dist/**/*.appchunk.js'
  - 'dist/**/*.js'
  - from: 'dist/'
    to: './'
    filter:
      - 'index.js'
      - 'preload.js'
      - '**/*.appchunk.js'
      - 'native/**/*.node'
nsis:
  artifactName: '${productName}-setup-${version}.${ext}'
  # We disable oneClick for this config so that the install directory differs for this version
  oneClick: false
win:
  icon: icon.ico
  target: nsis
  signExts:
    - dll
  signtoolOptions:
    certificateSubjectName: Fast Expo Collective LLC
    signingHashAlgorithms:
      - sha256
    rfc3161TimeStampServer: http://ts.ssl.com

# These properties differ between configs
productName: ShieldBattery-Staging
publish:
  provider: spaces
  name: shieldbattery-staging
  region: nyc3
  path: /app/
