# The electron-builder config for the staging site (https://dev.shieldbattery.net)
# It should generally match the other build configs (except things that need to differ for this
# "region")
appId: net.shieldbattery.client.dev
extraResources:
- game/dist/**
- "!game/dist/**/*.map"
files:
- "!**/*.map"
- "!build/**/*"
# Devtron and its deps bring in a *ton* of space hogging files, but aren't used in the packed app,
# so we manually strip them out. Bleh.
- "!node_modules/accessibility-developer-tools/**/*"
- "!node_modules/devtron/**/*"
- "!node_modules/highlight.js/**/*"
- "!node_modules/humanize-plus/**/*"
# babel-preset-env brings in caniuse-db, but its not necessary at runtime in our app
- "!node_modules/caniuse-db/**/*"
nsis:
  artifactName: "${productName}-setup-${version}.${ext}"
  # We disable oneClick for this config so that the install directory differs for this version
  oneClick: false
win:
  certificateSubjectName: Travis Collins
  icon: icon.ico
  target: nsis-web

# These properties differ between configs
productName: ShieldBattery-Dev
publish:
  provider: generic
  url: "https://dev.shieldbattery.net/published_artifacts/${os}/"
