// source: google/cloud/vision/v1/product_search.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_api_resource_pb = require('../../../../google/api/resource_pb.js');
goog.object.extend(proto, google_api_resource_pb);
var google_cloud_vision_v1_geometry_pb = require('../../../../google/cloud/vision/v1/geometry_pb.js');
goog.object.extend(proto, google_cloud_vision_v1_geometry_pb);
var google_cloud_vision_v1_product_search_service_pb = require('../../../../google/cloud/vision/v1/product_search_service_pb.js');
goog.object.extend(proto, google_cloud_vision_v1_product_search_service_pb);
var google_protobuf_timestamp_pb = require('google-protobuf/google/protobuf/timestamp_pb.js');
goog.object.extend(proto, google_protobuf_timestamp_pb);
goog.exportSymbol('proto.google.cloud.vision.v1.ProductSearchParams', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.ProductSearchResults', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.ProductSearchResults.Result', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.ProductSearchParams = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.vision.v1.ProductSearchParams.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.vision.v1.ProductSearchParams, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.ProductSearchParams.displayName = 'proto.google.cloud.vision.v1.ProductSearchParams';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.ProductSearchResults = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.vision.v1.ProductSearchResults.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.vision.v1.ProductSearchResults, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.ProductSearchResults.displayName = 'proto.google.cloud.vision.v1.ProductSearchResults';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.vision.v1.ProductSearchResults.Result, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.ProductSearchResults.Result.displayName = 'proto.google.cloud.vision.v1.ProductSearchResults.Result';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.displayName = 'proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.displayName = 'proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.vision.v1.ProductSearchParams.repeatedFields_ = [7];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.ProductSearchParams.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.ProductSearchParams.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.ProductSearchParams} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.ProductSearchParams.toObject = function(includeInstance, msg) {
  var f, obj = {
    boundingPoly: (f = msg.getBoundingPoly()) && google_cloud_vision_v1_geometry_pb.BoundingPoly.toObject(includeInstance, f),
    productSet: jspb.Message.getFieldWithDefault(msg, 6, ""),
    productCategoriesList: (f = jspb.Message.getRepeatedField(msg, 7)) == null ? undefined : f,
    filter: jspb.Message.getFieldWithDefault(msg, 8, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.ProductSearchParams}
 */
proto.google.cloud.vision.v1.ProductSearchParams.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.ProductSearchParams;
  return proto.google.cloud.vision.v1.ProductSearchParams.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.ProductSearchParams} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.ProductSearchParams}
 */
proto.google.cloud.vision.v1.ProductSearchParams.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 9:
      var value = new google_cloud_vision_v1_geometry_pb.BoundingPoly;
      reader.readMessage(value,google_cloud_vision_v1_geometry_pb.BoundingPoly.deserializeBinaryFromReader);
      msg.setBoundingPoly(value);
      break;
    case 6:
      var value = /** @type {string} */ (reader.readString());
      msg.setProductSet(value);
      break;
    case 7:
      var value = /** @type {string} */ (reader.readString());
      msg.addProductCategories(value);
      break;
    case 8:
      var value = /** @type {string} */ (reader.readString());
      msg.setFilter(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.ProductSearchParams.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.ProductSearchParams.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.ProductSearchParams} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.ProductSearchParams.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBoundingPoly();
  if (f != null) {
    writer.writeMessage(
      9,
      f,
      google_cloud_vision_v1_geometry_pb.BoundingPoly.serializeBinaryToWriter
    );
  }
  f = message.getProductSet();
  if (f.length > 0) {
    writer.writeString(
      6,
      f
    );
  }
  f = message.getProductCategoriesList();
  if (f.length > 0) {
    writer.writeRepeatedString(
      7,
      f
    );
  }
  f = message.getFilter();
  if (f.length > 0) {
    writer.writeString(
      8,
      f
    );
  }
};


/**
 * optional BoundingPoly bounding_poly = 9;
 * @return {?proto.google.cloud.vision.v1.BoundingPoly}
 */
proto.google.cloud.vision.v1.ProductSearchParams.prototype.getBoundingPoly = function() {
  return /** @type{?proto.google.cloud.vision.v1.BoundingPoly} */ (
    jspb.Message.getWrapperField(this, google_cloud_vision_v1_geometry_pb.BoundingPoly, 9));
};


/**
 * @param {?proto.google.cloud.vision.v1.BoundingPoly|undefined} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchParams} returns this
*/
proto.google.cloud.vision.v1.ProductSearchParams.prototype.setBoundingPoly = function(value) {
  return jspb.Message.setWrapperField(this, 9, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.ProductSearchParams} returns this
 */
proto.google.cloud.vision.v1.ProductSearchParams.prototype.clearBoundingPoly = function() {
  return this.setBoundingPoly(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.ProductSearchParams.prototype.hasBoundingPoly = function() {
  return jspb.Message.getField(this, 9) != null;
};


/**
 * optional string product_set = 6;
 * @return {string}
 */
proto.google.cloud.vision.v1.ProductSearchParams.prototype.getProductSet = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 6, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchParams} returns this
 */
proto.google.cloud.vision.v1.ProductSearchParams.prototype.setProductSet = function(value) {
  return jspb.Message.setProto3StringField(this, 6, value);
};


/**
 * repeated string product_categories = 7;
 * @return {!Array<string>}
 */
proto.google.cloud.vision.v1.ProductSearchParams.prototype.getProductCategoriesList = function() {
  return /** @type {!Array<string>} */ (jspb.Message.getRepeatedField(this, 7));
};


/**
 * @param {!Array<string>} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchParams} returns this
 */
proto.google.cloud.vision.v1.ProductSearchParams.prototype.setProductCategoriesList = function(value) {
  return jspb.Message.setField(this, 7, value || []);
};


/**
 * @param {string} value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.ProductSearchParams} returns this
 */
proto.google.cloud.vision.v1.ProductSearchParams.prototype.addProductCategories = function(value, opt_index) {
  return jspb.Message.addToRepeatedField(this, 7, value, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.ProductSearchParams} returns this
 */
proto.google.cloud.vision.v1.ProductSearchParams.prototype.clearProductCategoriesList = function() {
  return this.setProductCategoriesList([]);
};


/**
 * optional string filter = 8;
 * @return {string}
 */
proto.google.cloud.vision.v1.ProductSearchParams.prototype.getFilter = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 8, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchParams} returns this
 */
proto.google.cloud.vision.v1.ProductSearchParams.prototype.setFilter = function(value) {
  return jspb.Message.setProto3StringField(this, 8, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.vision.v1.ProductSearchResults.repeatedFields_ = [5,6];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.ProductSearchResults.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.ProductSearchResults.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.ProductSearchResults.toObject = function(includeInstance, msg) {
  var f, obj = {
    indexTime: (f = msg.getIndexTime()) && google_protobuf_timestamp_pb.Timestamp.toObject(includeInstance, f),
    resultsList: jspb.Message.toObjectList(msg.getResultsList(),
    proto.google.cloud.vision.v1.ProductSearchResults.Result.toObject, includeInstance),
    productGroupedResultsList: jspb.Message.toObjectList(msg.getProductGroupedResultsList(),
    proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults}
 */
proto.google.cloud.vision.v1.ProductSearchResults.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.ProductSearchResults;
  return proto.google.cloud.vision.v1.ProductSearchResults.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults}
 */
proto.google.cloud.vision.v1.ProductSearchResults.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 2:
      var value = new google_protobuf_timestamp_pb.Timestamp;
      reader.readMessage(value,google_protobuf_timestamp_pb.Timestamp.deserializeBinaryFromReader);
      msg.setIndexTime(value);
      break;
    case 5:
      var value = new proto.google.cloud.vision.v1.ProductSearchResults.Result;
      reader.readMessage(value,proto.google.cloud.vision.v1.ProductSearchResults.Result.deserializeBinaryFromReader);
      msg.addResults(value);
      break;
    case 6:
      var value = new proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult;
      reader.readMessage(value,proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.deserializeBinaryFromReader);
      msg.addProductGroupedResults(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.ProductSearchResults.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.ProductSearchResults.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.ProductSearchResults.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getIndexTime();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_protobuf_timestamp_pb.Timestamp.serializeBinaryToWriter
    );
  }
  f = message.getResultsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.google.cloud.vision.v1.ProductSearchResults.Result.serializeBinaryToWriter
    );
  }
  f = message.getProductGroupedResultsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.ProductSearchResults.Result.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults.Result} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result.toObject = function(includeInstance, msg) {
  var f, obj = {
    product: (f = msg.getProduct()) && google_cloud_vision_v1_product_search_service_pb.Product.toObject(includeInstance, f),
    score: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    image: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.Result}
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.ProductSearchResults.Result;
  return proto.google.cloud.vision.v1.ProductSearchResults.Result.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults.Result} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.Result}
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_cloud_vision_v1_product_search_service_pb.Product;
      reader.readMessage(value,google_cloud_vision_v1_product_search_service_pb.Product.deserializeBinaryFromReader);
      msg.setProduct(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setScore(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setImage(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.ProductSearchResults.Result.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults.Result} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProduct();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_cloud_vision_v1_product_search_service_pb.Product.serializeBinaryToWriter
    );
  }
  f = message.getScore();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getImage();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional Product product = 1;
 * @return {?proto.google.cloud.vision.v1.Product}
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result.prototype.getProduct = function() {
  return /** @type{?proto.google.cloud.vision.v1.Product} */ (
    jspb.Message.getWrapperField(this, google_cloud_vision_v1_product_search_service_pb.Product, 1));
};


/**
 * @param {?proto.google.cloud.vision.v1.Product|undefined} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.Result} returns this
*/
proto.google.cloud.vision.v1.ProductSearchResults.Result.prototype.setProduct = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.Result} returns this
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result.prototype.clearProduct = function() {
  return this.setProduct(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result.prototype.hasProduct = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional float score = 2;
 * @return {number}
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result.prototype.getScore = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.Result} returns this
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result.prototype.setScore = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional string image = 3;
 * @return {string}
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result.prototype.getImage = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.Result} returns this
 */
proto.google.cloud.vision.v1.ProductSearchResults.Result.prototype.setImage = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.toObject = function(includeInstance, msg) {
  var f, obj = {
    mid: jspb.Message.getFieldWithDefault(msg, 1, ""),
    languageCode: jspb.Message.getFieldWithDefault(msg, 2, ""),
    name: jspb.Message.getFieldWithDefault(msg, 3, ""),
    score: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation}
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation;
  return proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation}
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setMid(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguageCode(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setName(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setScore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getMid();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLanguageCode();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
  f = message.getName();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getScore();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * optional string mid = 1;
 * @return {string}
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.prototype.getMid = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation} returns this
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.prototype.setMid = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string language_code = 2;
 * @return {string}
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.prototype.getLanguageCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation} returns this
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.prototype.setLanguageCode = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * optional string name = 3;
 * @return {string}
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.prototype.getName = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation} returns this
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.prototype.setName = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional float score = 4;
 * @return {number}
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.prototype.getScore = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation} returns this
 */
proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.prototype.setScore = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.repeatedFields_ = [2,3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.toObject = function(includeInstance, msg) {
  var f, obj = {
    boundingPoly: (f = msg.getBoundingPoly()) && google_cloud_vision_v1_geometry_pb.BoundingPoly.toObject(includeInstance, f),
    resultsList: jspb.Message.toObjectList(msg.getResultsList(),
    proto.google.cloud.vision.v1.ProductSearchResults.Result.toObject, includeInstance),
    objectAnnotationsList: jspb.Message.toObjectList(msg.getObjectAnnotationsList(),
    proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult}
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult;
  return proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult}
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new google_cloud_vision_v1_geometry_pb.BoundingPoly;
      reader.readMessage(value,google_cloud_vision_v1_geometry_pb.BoundingPoly.deserializeBinaryFromReader);
      msg.setBoundingPoly(value);
      break;
    case 2:
      var value = new proto.google.cloud.vision.v1.ProductSearchResults.Result;
      reader.readMessage(value,proto.google.cloud.vision.v1.ProductSearchResults.Result.deserializeBinaryFromReader);
      msg.addResults(value);
      break;
    case 3:
      var value = new proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation;
      reader.readMessage(value,proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.deserializeBinaryFromReader);
      msg.addObjectAnnotations(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getBoundingPoly();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      google_cloud_vision_v1_geometry_pb.BoundingPoly.serializeBinaryToWriter
    );
  }
  f = message.getResultsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.google.cloud.vision.v1.ProductSearchResults.Result.serializeBinaryToWriter
    );
  }
  f = message.getObjectAnnotationsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation.serializeBinaryToWriter
    );
  }
};


/**
 * optional BoundingPoly bounding_poly = 1;
 * @return {?proto.google.cloud.vision.v1.BoundingPoly}
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.getBoundingPoly = function() {
  return /** @type{?proto.google.cloud.vision.v1.BoundingPoly} */ (
    jspb.Message.getWrapperField(this, google_cloud_vision_v1_geometry_pb.BoundingPoly, 1));
};


/**
 * @param {?proto.google.cloud.vision.v1.BoundingPoly|undefined} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult} returns this
*/
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.setBoundingPoly = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult} returns this
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.clearBoundingPoly = function() {
  return this.setBoundingPoly(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.hasBoundingPoly = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * repeated Result results = 2;
 * @return {!Array<!proto.google.cloud.vision.v1.ProductSearchResults.Result>}
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.getResultsList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.ProductSearchResults.Result>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.ProductSearchResults.Result, 2));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.ProductSearchResults.Result>} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult} returns this
*/
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.setResultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults.Result=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.Result}
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.addResults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.cloud.vision.v1.ProductSearchResults.Result, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult} returns this
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.clearResultsList = function() {
  return this.setResultsList([]);
};


/**
 * repeated ObjectAnnotation object_annotations = 3;
 * @return {!Array<!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation>}
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.getObjectAnnotationsList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation, 3));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation>} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult} returns this
*/
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.setObjectAnnotationsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation}
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.addObjectAnnotations = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.cloud.vision.v1.ProductSearchResults.ObjectAnnotation, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult} returns this
 */
proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult.prototype.clearObjectAnnotationsList = function() {
  return this.setObjectAnnotationsList([]);
};


/**
 * optional google.protobuf.Timestamp index_time = 2;
 * @return {?proto.google.protobuf.Timestamp}
 */
proto.google.cloud.vision.v1.ProductSearchResults.prototype.getIndexTime = function() {
  return /** @type{?proto.google.protobuf.Timestamp} */ (
    jspb.Message.getWrapperField(this, google_protobuf_timestamp_pb.Timestamp, 2));
};


/**
 * @param {?proto.google.protobuf.Timestamp|undefined} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults} returns this
*/
proto.google.cloud.vision.v1.ProductSearchResults.prototype.setIndexTime = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults} returns this
 */
proto.google.cloud.vision.v1.ProductSearchResults.prototype.clearIndexTime = function() {
  return this.setIndexTime(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.ProductSearchResults.prototype.hasIndexTime = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Result results = 5;
 * @return {!Array<!proto.google.cloud.vision.v1.ProductSearchResults.Result>}
 */
proto.google.cloud.vision.v1.ProductSearchResults.prototype.getResultsList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.ProductSearchResults.Result>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.ProductSearchResults.Result, 5));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.ProductSearchResults.Result>} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults} returns this
*/
proto.google.cloud.vision.v1.ProductSearchResults.prototype.setResultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults.Result=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.Result}
 */
proto.google.cloud.vision.v1.ProductSearchResults.prototype.addResults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.google.cloud.vision.v1.ProductSearchResults.Result, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults} returns this
 */
proto.google.cloud.vision.v1.ProductSearchResults.prototype.clearResultsList = function() {
  return this.setResultsList([]);
};


/**
 * repeated GroupedResult product_grouped_results = 6;
 * @return {!Array<!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult>}
 */
proto.google.cloud.vision.v1.ProductSearchResults.prototype.getProductGroupedResultsList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult, 6));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult>} value
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults} returns this
*/
proto.google.cloud.vision.v1.ProductSearchResults.prototype.setProductGroupedResultsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult}
 */
proto.google.cloud.vision.v1.ProductSearchResults.prototype.addProductGroupedResults = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.google.cloud.vision.v1.ProductSearchResults.GroupedResult, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.ProductSearchResults} returns this
 */
proto.google.cloud.vision.v1.ProductSearchResults.prototype.clearProductGroupedResultsList = function() {
  return this.setProductGroupedResultsList([]);
};


goog.object.extend(exports, proto.google.cloud.vision.v1);
