// source: google/cloud/vision/v1/text_annotation.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

var google_cloud_vision_v1_geometry_pb = require('../../../../google/cloud/vision/v1/geometry_pb.js');
goog.object.extend(proto, google_cloud_vision_v1_geometry_pb);
goog.exportSymbol('proto.google.cloud.vision.v1.Block', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.Block.BlockType', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.Page', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.Paragraph', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.Symbol', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.TextAnnotation', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.BreakType', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.TextAnnotation.TextProperty', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.Word', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.TextAnnotation = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.vision.v1.TextAnnotation.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.vision.v1.TextAnnotation, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.TextAnnotation.displayName = 'proto.google.cloud.vision.v1.TextAnnotation';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.displayName = 'proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.displayName = 'proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.vision.v1.TextAnnotation.TextProperty.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.vision.v1.TextAnnotation.TextProperty, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.TextAnnotation.TextProperty.displayName = 'proto.google.cloud.vision.v1.TextAnnotation.TextProperty';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.Page = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.vision.v1.Page.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.vision.v1.Page, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.Page.displayName = 'proto.google.cloud.vision.v1.Page';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.Block = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.vision.v1.Block.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.vision.v1.Block, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.Block.displayName = 'proto.google.cloud.vision.v1.Block';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.Paragraph = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.vision.v1.Paragraph.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.vision.v1.Paragraph, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.Paragraph.displayName = 'proto.google.cloud.vision.v1.Paragraph';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.Word = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.vision.v1.Word.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.vision.v1.Word, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.Word.displayName = 'proto.google.cloud.vision.v1.Word';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.Symbol = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.vision.v1.Symbol, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.Symbol.displayName = 'proto.google.cloud.vision.v1.Symbol';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.vision.v1.TextAnnotation.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.TextAnnotation.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.TextAnnotation.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.TextAnnotation} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.TextAnnotation.toObject = function(includeInstance, msg) {
  var f, obj = {
    pagesList: jspb.Message.toObjectList(msg.getPagesList(),
    proto.google.cloud.vision.v1.Page.toObject, includeInstance),
    text: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.TextAnnotation}
 */
proto.google.cloud.vision.v1.TextAnnotation.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.TextAnnotation;
  return proto.google.cloud.vision.v1.TextAnnotation.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.TextAnnotation} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.TextAnnotation}
 */
proto.google.cloud.vision.v1.TextAnnotation.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.cloud.vision.v1.Page;
      reader.readMessage(value,proto.google.cloud.vision.v1.Page.deserializeBinaryFromReader);
      msg.addPages(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.TextAnnotation.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.TextAnnotation.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.TextAnnotation} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.TextAnnotation.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getPagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.google.cloud.vision.v1.Page.serializeBinaryToWriter
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.toObject = function(includeInstance, msg) {
  var f, obj = {
    languageCode: jspb.Message.getFieldWithDefault(msg, 1, ""),
    confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage}
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage;
  return proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage}
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguageCode(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLanguageCode();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
};


/**
 * optional string language_code = 1;
 * @return {string}
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.prototype.getLanguageCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage} returns this
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.prototype.setLanguageCode = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float confidence = 2;
 * @return {number}
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage} returns this
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.toObject = function(includeInstance, msg) {
  var f, obj = {
    type: jspb.Message.getFieldWithDefault(msg, 1, 0),
    isPrefix: jspb.Message.getBooleanFieldWithDefault(msg, 2, false)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak}
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak;
  return proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak}
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {!proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.BreakType} */ (reader.readEnum());
      msg.setType(value);
      break;
    case 2:
      var value = /** @type {boolean} */ (reader.readBool());
      msg.setIsPrefix(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getType();
  if (f !== 0.0) {
    writer.writeEnum(
      1,
      f
    );
  }
  f = message.getIsPrefix();
  if (f) {
    writer.writeBool(
      2,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.BreakType = {
  UNKNOWN: 0,
  SPACE: 1,
  SURE_SPACE: 2,
  EOL_SURE_SPACE: 3,
  HYPHEN: 4,
  LINE_BREAK: 5
};

/**
 * optional BreakType type = 1;
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.BreakType}
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.prototype.getType = function() {
  return /** @type {!proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.BreakType} */ (jspb.Message.getFieldWithDefault(this, 1, 0));
};


/**
 * @param {!proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.BreakType} value
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak} returns this
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.prototype.setType = function(value) {
  return jspb.Message.setProto3EnumField(this, 1, value);
};


/**
 * optional bool is_prefix = 2;
 * @return {boolean}
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.prototype.getIsPrefix = function() {
  return /** @type {boolean} */ (jspb.Message.getBooleanFieldWithDefault(this, 2, false));
};


/**
 * @param {boolean} value
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak} returns this
 */
proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.prototype.setIsPrefix = function(value) {
  return jspb.Message.setProto3BooleanField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.repeatedFields_ = [1];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.TextAnnotation.TextProperty.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.TextAnnotation.TextProperty} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.toObject = function(includeInstance, msg) {
  var f, obj = {
    detectedLanguagesList: jspb.Message.toObjectList(msg.getDetectedLanguagesList(),
    proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.toObject, includeInstance),
    detectedBreak: (f = msg.getDetectedBreak()) && proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.toObject(includeInstance, f)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.TextProperty}
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.TextAnnotation.TextProperty;
  return proto.google.cloud.vision.v1.TextAnnotation.TextProperty.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.TextAnnotation.TextProperty} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.TextProperty}
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage;
      reader.readMessage(value,proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.deserializeBinaryFromReader);
      msg.addDetectedLanguages(value);
      break;
    case 2:
      var value = new proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak;
      reader.readMessage(value,proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.deserializeBinaryFromReader);
      msg.setDetectedBreak(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.TextAnnotation.TextProperty.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.TextAnnotation.TextProperty} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getDetectedLanguagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage.serializeBinaryToWriter
    );
  }
  f = message.getDetectedBreak();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak.serializeBinaryToWriter
    );
  }
};


/**
 * repeated DetectedLanguage detected_languages = 1;
 * @return {!Array<!proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage>}
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.prototype.getDetectedLanguagesList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage, 1));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage>} value
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.TextProperty} returns this
*/
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.prototype.setDetectedLanguagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage}
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.prototype.addDetectedLanguages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.cloud.vision.v1.TextAnnotation.DetectedLanguage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.TextProperty} returns this
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.prototype.clearDetectedLanguagesList = function() {
  return this.setDetectedLanguagesList([]);
};


/**
 * optional DetectedBreak detected_break = 2;
 * @return {?proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak}
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.prototype.getDetectedBreak = function() {
  return /** @type{?proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak, 2));
};


/**
 * @param {?proto.google.cloud.vision.v1.TextAnnotation.DetectedBreak|undefined} value
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.TextProperty} returns this
*/
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.prototype.setDetectedBreak = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.TextAnnotation.TextProperty} returns this
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.prototype.clearDetectedBreak = function() {
  return this.setDetectedBreak(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.TextAnnotation.TextProperty.prototype.hasDetectedBreak = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Page pages = 1;
 * @return {!Array<!proto.google.cloud.vision.v1.Page>}
 */
proto.google.cloud.vision.v1.TextAnnotation.prototype.getPagesList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.Page>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.Page, 1));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.Page>} value
 * @return {!proto.google.cloud.vision.v1.TextAnnotation} returns this
*/
proto.google.cloud.vision.v1.TextAnnotation.prototype.setPagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.Page=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.Page}
 */
proto.google.cloud.vision.v1.TextAnnotation.prototype.addPages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.cloud.vision.v1.Page, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.TextAnnotation} returns this
 */
proto.google.cloud.vision.v1.TextAnnotation.prototype.clearPagesList = function() {
  return this.setPagesList([]);
};


/**
 * optional string text = 2;
 * @return {string}
 */
proto.google.cloud.vision.v1.TextAnnotation.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.TextAnnotation} returns this
 */
proto.google.cloud.vision.v1.TextAnnotation.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.vision.v1.Page.repeatedFields_ = [4];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.Page.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.Page.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.Page} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.Page.toObject = function(includeInstance, msg) {
  var f, obj = {
    property: (f = msg.getProperty()) && proto.google.cloud.vision.v1.TextAnnotation.TextProperty.toObject(includeInstance, f),
    width: jspb.Message.getFieldWithDefault(msg, 2, 0),
    height: jspb.Message.getFieldWithDefault(msg, 3, 0),
    blocksList: jspb.Message.toObjectList(msg.getBlocksList(),
    proto.google.cloud.vision.v1.Block.toObject, includeInstance),
    confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.Page}
 */
proto.google.cloud.vision.v1.Page.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.Page;
  return proto.google.cloud.vision.v1.Page.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.Page} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.Page}
 */
proto.google.cloud.vision.v1.Page.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.cloud.vision.v1.TextAnnotation.TextProperty;
      reader.readMessage(value,proto.google.cloud.vision.v1.TextAnnotation.TextProperty.deserializeBinaryFromReader);
      msg.setProperty(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setWidth(value);
      break;
    case 3:
      var value = /** @type {number} */ (reader.readInt32());
      msg.setHeight(value);
      break;
    case 4:
      var value = new proto.google.cloud.vision.v1.Block;
      reader.readMessage(value,proto.google.cloud.vision.v1.Block.deserializeBinaryFromReader);
      msg.addBlocks(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.Page.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.Page.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.Page} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.Page.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProperty();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.cloud.vision.v1.TextAnnotation.TextProperty.serializeBinaryToWriter
    );
  }
  f = message.getWidth();
  if (f !== 0) {
    writer.writeInt32(
      2,
      f
    );
  }
  f = message.getHeight();
  if (f !== 0) {
    writer.writeInt32(
      3,
      f
    );
  }
  f = message.getBlocksList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.google.cloud.vision.v1.Block.serializeBinaryToWriter
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
};


/**
 * optional TextAnnotation.TextProperty property = 1;
 * @return {?proto.google.cloud.vision.v1.TextAnnotation.TextProperty}
 */
proto.google.cloud.vision.v1.Page.prototype.getProperty = function() {
  return /** @type{?proto.google.cloud.vision.v1.TextAnnotation.TextProperty} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.vision.v1.TextAnnotation.TextProperty, 1));
};


/**
 * @param {?proto.google.cloud.vision.v1.TextAnnotation.TextProperty|undefined} value
 * @return {!proto.google.cloud.vision.v1.Page} returns this
*/
proto.google.cloud.vision.v1.Page.prototype.setProperty = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.Page} returns this
 */
proto.google.cloud.vision.v1.Page.prototype.clearProperty = function() {
  return this.setProperty(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.Page.prototype.hasProperty = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional int32 width = 2;
 * @return {number}
 */
proto.google.cloud.vision.v1.Page.prototype.getWidth = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 2, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.vision.v1.Page} returns this
 */
proto.google.cloud.vision.v1.Page.prototype.setWidth = function(value) {
  return jspb.Message.setProto3IntField(this, 2, value);
};


/**
 * optional int32 height = 3;
 * @return {number}
 */
proto.google.cloud.vision.v1.Page.prototype.getHeight = function() {
  return /** @type {number} */ (jspb.Message.getFieldWithDefault(this, 3, 0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.vision.v1.Page} returns this
 */
proto.google.cloud.vision.v1.Page.prototype.setHeight = function(value) {
  return jspb.Message.setProto3IntField(this, 3, value);
};


/**
 * repeated Block blocks = 4;
 * @return {!Array<!proto.google.cloud.vision.v1.Block>}
 */
proto.google.cloud.vision.v1.Page.prototype.getBlocksList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.Block>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.Block, 4));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.Block>} value
 * @return {!proto.google.cloud.vision.v1.Page} returns this
*/
proto.google.cloud.vision.v1.Page.prototype.setBlocksList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.Block=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.Block}
 */
proto.google.cloud.vision.v1.Page.prototype.addBlocks = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.google.cloud.vision.v1.Block, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.Page} returns this
 */
proto.google.cloud.vision.v1.Page.prototype.clearBlocksList = function() {
  return this.setBlocksList([]);
};


/**
 * optional float confidence = 5;
 * @return {number}
 */
proto.google.cloud.vision.v1.Page.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.vision.v1.Page} returns this
 */
proto.google.cloud.vision.v1.Page.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.vision.v1.Block.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.Block.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.Block.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.Block} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.Block.toObject = function(includeInstance, msg) {
  var f, obj = {
    property: (f = msg.getProperty()) && proto.google.cloud.vision.v1.TextAnnotation.TextProperty.toObject(includeInstance, f),
    boundingBox: (f = msg.getBoundingBox()) && google_cloud_vision_v1_geometry_pb.BoundingPoly.toObject(includeInstance, f),
    paragraphsList: jspb.Message.toObjectList(msg.getParagraphsList(),
    proto.google.cloud.vision.v1.Paragraph.toObject, includeInstance),
    blockType: jspb.Message.getFieldWithDefault(msg, 4, 0),
    confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 5, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.Block}
 */
proto.google.cloud.vision.v1.Block.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.Block;
  return proto.google.cloud.vision.v1.Block.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.Block} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.Block}
 */
proto.google.cloud.vision.v1.Block.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.cloud.vision.v1.TextAnnotation.TextProperty;
      reader.readMessage(value,proto.google.cloud.vision.v1.TextAnnotation.TextProperty.deserializeBinaryFromReader);
      msg.setProperty(value);
      break;
    case 2:
      var value = new google_cloud_vision_v1_geometry_pb.BoundingPoly;
      reader.readMessage(value,google_cloud_vision_v1_geometry_pb.BoundingPoly.deserializeBinaryFromReader);
      msg.setBoundingBox(value);
      break;
    case 3:
      var value = new proto.google.cloud.vision.v1.Paragraph;
      reader.readMessage(value,proto.google.cloud.vision.v1.Paragraph.deserializeBinaryFromReader);
      msg.addParagraphs(value);
      break;
    case 4:
      var value = /** @type {!proto.google.cloud.vision.v1.Block.BlockType} */ (reader.readEnum());
      msg.setBlockType(value);
      break;
    case 5:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.Block.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.Block.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.Block} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.Block.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProperty();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.cloud.vision.v1.TextAnnotation.TextProperty.serializeBinaryToWriter
    );
  }
  f = message.getBoundingBox();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_cloud_vision_v1_geometry_pb.BoundingPoly.serializeBinaryToWriter
    );
  }
  f = message.getParagraphsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.google.cloud.vision.v1.Paragraph.serializeBinaryToWriter
    );
  }
  f = message.getBlockType();
  if (f !== 0.0) {
    writer.writeEnum(
      4,
      f
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeFloat(
      5,
      f
    );
  }
};


/**
 * @enum {number}
 */
proto.google.cloud.vision.v1.Block.BlockType = {
  UNKNOWN: 0,
  TEXT: 1,
  TABLE: 2,
  PICTURE: 3,
  RULER: 4,
  BARCODE: 5
};

/**
 * optional TextAnnotation.TextProperty property = 1;
 * @return {?proto.google.cloud.vision.v1.TextAnnotation.TextProperty}
 */
proto.google.cloud.vision.v1.Block.prototype.getProperty = function() {
  return /** @type{?proto.google.cloud.vision.v1.TextAnnotation.TextProperty} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.vision.v1.TextAnnotation.TextProperty, 1));
};


/**
 * @param {?proto.google.cloud.vision.v1.TextAnnotation.TextProperty|undefined} value
 * @return {!proto.google.cloud.vision.v1.Block} returns this
*/
proto.google.cloud.vision.v1.Block.prototype.setProperty = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.Block} returns this
 */
proto.google.cloud.vision.v1.Block.prototype.clearProperty = function() {
  return this.setProperty(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.Block.prototype.hasProperty = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional BoundingPoly bounding_box = 2;
 * @return {?proto.google.cloud.vision.v1.BoundingPoly}
 */
proto.google.cloud.vision.v1.Block.prototype.getBoundingBox = function() {
  return /** @type{?proto.google.cloud.vision.v1.BoundingPoly} */ (
    jspb.Message.getWrapperField(this, google_cloud_vision_v1_geometry_pb.BoundingPoly, 2));
};


/**
 * @param {?proto.google.cloud.vision.v1.BoundingPoly|undefined} value
 * @return {!proto.google.cloud.vision.v1.Block} returns this
*/
proto.google.cloud.vision.v1.Block.prototype.setBoundingBox = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.Block} returns this
 */
proto.google.cloud.vision.v1.Block.prototype.clearBoundingBox = function() {
  return this.setBoundingBox(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.Block.prototype.hasBoundingBox = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Paragraph paragraphs = 3;
 * @return {!Array<!proto.google.cloud.vision.v1.Paragraph>}
 */
proto.google.cloud.vision.v1.Block.prototype.getParagraphsList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.Paragraph>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.Paragraph, 3));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.Paragraph>} value
 * @return {!proto.google.cloud.vision.v1.Block} returns this
*/
proto.google.cloud.vision.v1.Block.prototype.setParagraphsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.Paragraph=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.Paragraph}
 */
proto.google.cloud.vision.v1.Block.prototype.addParagraphs = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.cloud.vision.v1.Paragraph, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.Block} returns this
 */
proto.google.cloud.vision.v1.Block.prototype.clearParagraphsList = function() {
  return this.setParagraphsList([]);
};


/**
 * optional BlockType block_type = 4;
 * @return {!proto.google.cloud.vision.v1.Block.BlockType}
 */
proto.google.cloud.vision.v1.Block.prototype.getBlockType = function() {
  return /** @type {!proto.google.cloud.vision.v1.Block.BlockType} */ (jspb.Message.getFieldWithDefault(this, 4, 0));
};


/**
 * @param {!proto.google.cloud.vision.v1.Block.BlockType} value
 * @return {!proto.google.cloud.vision.v1.Block} returns this
 */
proto.google.cloud.vision.v1.Block.prototype.setBlockType = function(value) {
  return jspb.Message.setProto3EnumField(this, 4, value);
};


/**
 * optional float confidence = 5;
 * @return {number}
 */
proto.google.cloud.vision.v1.Block.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 5, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.vision.v1.Block} returns this
 */
proto.google.cloud.vision.v1.Block.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 5, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.vision.v1.Paragraph.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.Paragraph.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.Paragraph.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.Paragraph} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.Paragraph.toObject = function(includeInstance, msg) {
  var f, obj = {
    property: (f = msg.getProperty()) && proto.google.cloud.vision.v1.TextAnnotation.TextProperty.toObject(includeInstance, f),
    boundingBox: (f = msg.getBoundingBox()) && google_cloud_vision_v1_geometry_pb.BoundingPoly.toObject(includeInstance, f),
    wordsList: jspb.Message.toObjectList(msg.getWordsList(),
    proto.google.cloud.vision.v1.Word.toObject, includeInstance),
    confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.Paragraph}
 */
proto.google.cloud.vision.v1.Paragraph.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.Paragraph;
  return proto.google.cloud.vision.v1.Paragraph.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.Paragraph} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.Paragraph}
 */
proto.google.cloud.vision.v1.Paragraph.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.cloud.vision.v1.TextAnnotation.TextProperty;
      reader.readMessage(value,proto.google.cloud.vision.v1.TextAnnotation.TextProperty.deserializeBinaryFromReader);
      msg.setProperty(value);
      break;
    case 2:
      var value = new google_cloud_vision_v1_geometry_pb.BoundingPoly;
      reader.readMessage(value,google_cloud_vision_v1_geometry_pb.BoundingPoly.deserializeBinaryFromReader);
      msg.setBoundingBox(value);
      break;
    case 3:
      var value = new proto.google.cloud.vision.v1.Word;
      reader.readMessage(value,proto.google.cloud.vision.v1.Word.deserializeBinaryFromReader);
      msg.addWords(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.Paragraph.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.Paragraph.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.Paragraph} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.Paragraph.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProperty();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.cloud.vision.v1.TextAnnotation.TextProperty.serializeBinaryToWriter
    );
  }
  f = message.getBoundingBox();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_cloud_vision_v1_geometry_pb.BoundingPoly.serializeBinaryToWriter
    );
  }
  f = message.getWordsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.google.cloud.vision.v1.Word.serializeBinaryToWriter
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * optional TextAnnotation.TextProperty property = 1;
 * @return {?proto.google.cloud.vision.v1.TextAnnotation.TextProperty}
 */
proto.google.cloud.vision.v1.Paragraph.prototype.getProperty = function() {
  return /** @type{?proto.google.cloud.vision.v1.TextAnnotation.TextProperty} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.vision.v1.TextAnnotation.TextProperty, 1));
};


/**
 * @param {?proto.google.cloud.vision.v1.TextAnnotation.TextProperty|undefined} value
 * @return {!proto.google.cloud.vision.v1.Paragraph} returns this
*/
proto.google.cloud.vision.v1.Paragraph.prototype.setProperty = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.Paragraph} returns this
 */
proto.google.cloud.vision.v1.Paragraph.prototype.clearProperty = function() {
  return this.setProperty(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.Paragraph.prototype.hasProperty = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional BoundingPoly bounding_box = 2;
 * @return {?proto.google.cloud.vision.v1.BoundingPoly}
 */
proto.google.cloud.vision.v1.Paragraph.prototype.getBoundingBox = function() {
  return /** @type{?proto.google.cloud.vision.v1.BoundingPoly} */ (
    jspb.Message.getWrapperField(this, google_cloud_vision_v1_geometry_pb.BoundingPoly, 2));
};


/**
 * @param {?proto.google.cloud.vision.v1.BoundingPoly|undefined} value
 * @return {!proto.google.cloud.vision.v1.Paragraph} returns this
*/
proto.google.cloud.vision.v1.Paragraph.prototype.setBoundingBox = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.Paragraph} returns this
 */
proto.google.cloud.vision.v1.Paragraph.prototype.clearBoundingBox = function() {
  return this.setBoundingBox(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.Paragraph.prototype.hasBoundingBox = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Word words = 3;
 * @return {!Array<!proto.google.cloud.vision.v1.Word>}
 */
proto.google.cloud.vision.v1.Paragraph.prototype.getWordsList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.Word>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.Word, 3));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.Word>} value
 * @return {!proto.google.cloud.vision.v1.Paragraph} returns this
*/
proto.google.cloud.vision.v1.Paragraph.prototype.setWordsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.Word=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.Word}
 */
proto.google.cloud.vision.v1.Paragraph.prototype.addWords = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.cloud.vision.v1.Word, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.Paragraph} returns this
 */
proto.google.cloud.vision.v1.Paragraph.prototype.clearWordsList = function() {
  return this.setWordsList([]);
};


/**
 * optional float confidence = 4;
 * @return {number}
 */
proto.google.cloud.vision.v1.Paragraph.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.vision.v1.Paragraph} returns this
 */
proto.google.cloud.vision.v1.Paragraph.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.vision.v1.Word.repeatedFields_ = [3];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.Word.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.Word.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.Word} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.Word.toObject = function(includeInstance, msg) {
  var f, obj = {
    property: (f = msg.getProperty()) && proto.google.cloud.vision.v1.TextAnnotation.TextProperty.toObject(includeInstance, f),
    boundingBox: (f = msg.getBoundingBox()) && google_cloud_vision_v1_geometry_pb.BoundingPoly.toObject(includeInstance, f),
    symbolsList: jspb.Message.toObjectList(msg.getSymbolsList(),
    proto.google.cloud.vision.v1.Symbol.toObject, includeInstance),
    confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.Word}
 */
proto.google.cloud.vision.v1.Word.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.Word;
  return proto.google.cloud.vision.v1.Word.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.Word} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.Word}
 */
proto.google.cloud.vision.v1.Word.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.cloud.vision.v1.TextAnnotation.TextProperty;
      reader.readMessage(value,proto.google.cloud.vision.v1.TextAnnotation.TextProperty.deserializeBinaryFromReader);
      msg.setProperty(value);
      break;
    case 2:
      var value = new google_cloud_vision_v1_geometry_pb.BoundingPoly;
      reader.readMessage(value,google_cloud_vision_v1_geometry_pb.BoundingPoly.deserializeBinaryFromReader);
      msg.setBoundingBox(value);
      break;
    case 3:
      var value = new proto.google.cloud.vision.v1.Symbol;
      reader.readMessage(value,proto.google.cloud.vision.v1.Symbol.deserializeBinaryFromReader);
      msg.addSymbols(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.Word.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.Word.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.Word} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.Word.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProperty();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.cloud.vision.v1.TextAnnotation.TextProperty.serializeBinaryToWriter
    );
  }
  f = message.getBoundingBox();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_cloud_vision_v1_geometry_pb.BoundingPoly.serializeBinaryToWriter
    );
  }
  f = message.getSymbolsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.google.cloud.vision.v1.Symbol.serializeBinaryToWriter
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * optional TextAnnotation.TextProperty property = 1;
 * @return {?proto.google.cloud.vision.v1.TextAnnotation.TextProperty}
 */
proto.google.cloud.vision.v1.Word.prototype.getProperty = function() {
  return /** @type{?proto.google.cloud.vision.v1.TextAnnotation.TextProperty} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.vision.v1.TextAnnotation.TextProperty, 1));
};


/**
 * @param {?proto.google.cloud.vision.v1.TextAnnotation.TextProperty|undefined} value
 * @return {!proto.google.cloud.vision.v1.Word} returns this
*/
proto.google.cloud.vision.v1.Word.prototype.setProperty = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.Word} returns this
 */
proto.google.cloud.vision.v1.Word.prototype.clearProperty = function() {
  return this.setProperty(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.Word.prototype.hasProperty = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional BoundingPoly bounding_box = 2;
 * @return {?proto.google.cloud.vision.v1.BoundingPoly}
 */
proto.google.cloud.vision.v1.Word.prototype.getBoundingBox = function() {
  return /** @type{?proto.google.cloud.vision.v1.BoundingPoly} */ (
    jspb.Message.getWrapperField(this, google_cloud_vision_v1_geometry_pb.BoundingPoly, 2));
};


/**
 * @param {?proto.google.cloud.vision.v1.BoundingPoly|undefined} value
 * @return {!proto.google.cloud.vision.v1.Word} returns this
*/
proto.google.cloud.vision.v1.Word.prototype.setBoundingBox = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.Word} returns this
 */
proto.google.cloud.vision.v1.Word.prototype.clearBoundingBox = function() {
  return this.setBoundingBox(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.Word.prototype.hasBoundingBox = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * repeated Symbol symbols = 3;
 * @return {!Array<!proto.google.cloud.vision.v1.Symbol>}
 */
proto.google.cloud.vision.v1.Word.prototype.getSymbolsList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.Symbol>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.Symbol, 3));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.Symbol>} value
 * @return {!proto.google.cloud.vision.v1.Word} returns this
*/
proto.google.cloud.vision.v1.Word.prototype.setSymbolsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.Symbol=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.Symbol}
 */
proto.google.cloud.vision.v1.Word.prototype.addSymbols = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.cloud.vision.v1.Symbol, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.Word} returns this
 */
proto.google.cloud.vision.v1.Word.prototype.clearSymbolsList = function() {
  return this.setSymbolsList([]);
};


/**
 * optional float confidence = 4;
 * @return {number}
 */
proto.google.cloud.vision.v1.Word.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.vision.v1.Word} returns this
 */
proto.google.cloud.vision.v1.Word.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.Symbol.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.Symbol.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.Symbol} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.Symbol.toObject = function(includeInstance, msg) {
  var f, obj = {
    property: (f = msg.getProperty()) && proto.google.cloud.vision.v1.TextAnnotation.TextProperty.toObject(includeInstance, f),
    boundingBox: (f = msg.getBoundingBox()) && google_cloud_vision_v1_geometry_pb.BoundingPoly.toObject(includeInstance, f),
    text: jspb.Message.getFieldWithDefault(msg, 3, ""),
    confidence: jspb.Message.getFloatingPointFieldWithDefault(msg, 4, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.Symbol}
 */
proto.google.cloud.vision.v1.Symbol.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.Symbol;
  return proto.google.cloud.vision.v1.Symbol.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.Symbol} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.Symbol}
 */
proto.google.cloud.vision.v1.Symbol.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.cloud.vision.v1.TextAnnotation.TextProperty;
      reader.readMessage(value,proto.google.cloud.vision.v1.TextAnnotation.TextProperty.deserializeBinaryFromReader);
      msg.setProperty(value);
      break;
    case 2:
      var value = new google_cloud_vision_v1_geometry_pb.BoundingPoly;
      reader.readMessage(value,google_cloud_vision_v1_geometry_pb.BoundingPoly.deserializeBinaryFromReader);
      msg.setBoundingBox(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setText(value);
      break;
    case 4:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setConfidence(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.Symbol.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.Symbol.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.Symbol} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.Symbol.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getProperty();
  if (f != null) {
    writer.writeMessage(
      1,
      f,
      proto.google.cloud.vision.v1.TextAnnotation.TextProperty.serializeBinaryToWriter
    );
  }
  f = message.getBoundingBox();
  if (f != null) {
    writer.writeMessage(
      2,
      f,
      google_cloud_vision_v1_geometry_pb.BoundingPoly.serializeBinaryToWriter
    );
  }
  f = message.getText();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getConfidence();
  if (f !== 0.0) {
    writer.writeFloat(
      4,
      f
    );
  }
};


/**
 * optional TextAnnotation.TextProperty property = 1;
 * @return {?proto.google.cloud.vision.v1.TextAnnotation.TextProperty}
 */
proto.google.cloud.vision.v1.Symbol.prototype.getProperty = function() {
  return /** @type{?proto.google.cloud.vision.v1.TextAnnotation.TextProperty} */ (
    jspb.Message.getWrapperField(this, proto.google.cloud.vision.v1.TextAnnotation.TextProperty, 1));
};


/**
 * @param {?proto.google.cloud.vision.v1.TextAnnotation.TextProperty|undefined} value
 * @return {!proto.google.cloud.vision.v1.Symbol} returns this
*/
proto.google.cloud.vision.v1.Symbol.prototype.setProperty = function(value) {
  return jspb.Message.setWrapperField(this, 1, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.Symbol} returns this
 */
proto.google.cloud.vision.v1.Symbol.prototype.clearProperty = function() {
  return this.setProperty(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.Symbol.prototype.hasProperty = function() {
  return jspb.Message.getField(this, 1) != null;
};


/**
 * optional BoundingPoly bounding_box = 2;
 * @return {?proto.google.cloud.vision.v1.BoundingPoly}
 */
proto.google.cloud.vision.v1.Symbol.prototype.getBoundingBox = function() {
  return /** @type{?proto.google.cloud.vision.v1.BoundingPoly} */ (
    jspb.Message.getWrapperField(this, google_cloud_vision_v1_geometry_pb.BoundingPoly, 2));
};


/**
 * @param {?proto.google.cloud.vision.v1.BoundingPoly|undefined} value
 * @return {!proto.google.cloud.vision.v1.Symbol} returns this
*/
proto.google.cloud.vision.v1.Symbol.prototype.setBoundingBox = function(value) {
  return jspb.Message.setWrapperField(this, 2, value);
};


/**
 * Clears the message field making it undefined.
 * @return {!proto.google.cloud.vision.v1.Symbol} returns this
 */
proto.google.cloud.vision.v1.Symbol.prototype.clearBoundingBox = function() {
  return this.setBoundingBox(undefined);
};


/**
 * Returns whether this field is set.
 * @return {boolean}
 */
proto.google.cloud.vision.v1.Symbol.prototype.hasBoundingBox = function() {
  return jspb.Message.getField(this, 2) != null;
};


/**
 * optional string text = 3;
 * @return {string}
 */
proto.google.cloud.vision.v1.Symbol.prototype.getText = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.Symbol} returns this
 */
proto.google.cloud.vision.v1.Symbol.prototype.setText = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * optional float confidence = 4;
 * @return {number}
 */
proto.google.cloud.vision.v1.Symbol.prototype.getConfidence = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 4, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.vision.v1.Symbol} returns this
 */
proto.google.cloud.vision.v1.Symbol.prototype.setConfidence = function(value) {
  return jspb.Message.setProto3FloatField(this, 4, value);
};


goog.object.extend(exports, proto.google.cloud.vision.v1);
