// source: google/cloud/vision/v1/web_detection.proto
/**
 * @fileoverview
 * @enhanceable
 * @suppress {missingRequire} reports error on implicit type usages.
 * @suppress {messageConventions} JS Compiler reports an error if a variable or
 *     field starts with 'MSG_' and isn't a translatable message.
 * @public
 */
// GENERATED CODE -- DO NOT EDIT!
/* eslint-disable */
// @ts-nocheck

var jspb = require('google-protobuf');
var goog = jspb;
var global =
    (typeof globalThis !== 'undefined' && globalThis) ||
    (typeof window !== 'undefined' && window) ||
    (typeof global !== 'undefined' && global) ||
    (typeof self !== 'undefined' && self) ||
    (function () { return this; }).call(null) ||
    Function('return this')();

goog.exportSymbol('proto.google.cloud.vision.v1.WebDetection', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.WebDetection.WebEntity', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.WebDetection.WebImage', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.WebDetection.WebLabel', null, global);
goog.exportSymbol('proto.google.cloud.vision.v1.WebDetection.WebPage', null, global);
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.WebDetection = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.vision.v1.WebDetection.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.vision.v1.WebDetection, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.WebDetection.displayName = 'proto.google.cloud.vision.v1.WebDetection';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.WebDetection.WebEntity = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.vision.v1.WebDetection.WebEntity, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.WebDetection.WebEntity.displayName = 'proto.google.cloud.vision.v1.WebDetection.WebEntity';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.WebDetection.WebImage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.vision.v1.WebDetection.WebImage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.WebDetection.WebImage.displayName = 'proto.google.cloud.vision.v1.WebDetection.WebImage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.WebDetection.WebPage = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, proto.google.cloud.vision.v1.WebDetection.WebPage.repeatedFields_, null);
};
goog.inherits(proto.google.cloud.vision.v1.WebDetection.WebPage, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.WebDetection.WebPage.displayName = 'proto.google.cloud.vision.v1.WebDetection.WebPage';
}
/**
 * Generated by JsPbCodeGenerator.
 * @param {Array=} opt_data Optional initial data array, typically from a
 * server response, or constructed directly in Javascript. The array is used
 * in place and becomes part of the constructed object. It is not cloned.
 * If no data is provided, the constructed object will be empty, but still
 * valid.
 * @extends {jspb.Message}
 * @constructor
 */
proto.google.cloud.vision.v1.WebDetection.WebLabel = function(opt_data) {
  jspb.Message.initialize(this, opt_data, 0, -1, null, null);
};
goog.inherits(proto.google.cloud.vision.v1.WebDetection.WebLabel, jspb.Message);
if (goog.DEBUG && !COMPILED) {
  /**
   * @public
   * @override
   */
  proto.google.cloud.vision.v1.WebDetection.WebLabel.displayName = 'proto.google.cloud.vision.v1.WebDetection.WebLabel';
}

/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.vision.v1.WebDetection.repeatedFields_ = [1,2,3,4,6,8];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.WebDetection.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.WebDetection} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.WebDetection.toObject = function(includeInstance, msg) {
  var f, obj = {
    webEntitiesList: jspb.Message.toObjectList(msg.getWebEntitiesList(),
    proto.google.cloud.vision.v1.WebDetection.WebEntity.toObject, includeInstance),
    fullMatchingImagesList: jspb.Message.toObjectList(msg.getFullMatchingImagesList(),
    proto.google.cloud.vision.v1.WebDetection.WebImage.toObject, includeInstance),
    partialMatchingImagesList: jspb.Message.toObjectList(msg.getPartialMatchingImagesList(),
    proto.google.cloud.vision.v1.WebDetection.WebImage.toObject, includeInstance),
    pagesWithMatchingImagesList: jspb.Message.toObjectList(msg.getPagesWithMatchingImagesList(),
    proto.google.cloud.vision.v1.WebDetection.WebPage.toObject, includeInstance),
    visuallySimilarImagesList: jspb.Message.toObjectList(msg.getVisuallySimilarImagesList(),
    proto.google.cloud.vision.v1.WebDetection.WebImage.toObject, includeInstance),
    bestGuessLabelsList: jspb.Message.toObjectList(msg.getBestGuessLabelsList(),
    proto.google.cloud.vision.v1.WebDetection.WebLabel.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.WebDetection}
 */
proto.google.cloud.vision.v1.WebDetection.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.WebDetection;
  return proto.google.cloud.vision.v1.WebDetection.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.WebDetection} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.WebDetection}
 */
proto.google.cloud.vision.v1.WebDetection.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = new proto.google.cloud.vision.v1.WebDetection.WebEntity;
      reader.readMessage(value,proto.google.cloud.vision.v1.WebDetection.WebEntity.deserializeBinaryFromReader);
      msg.addWebEntities(value);
      break;
    case 2:
      var value = new proto.google.cloud.vision.v1.WebDetection.WebImage;
      reader.readMessage(value,proto.google.cloud.vision.v1.WebDetection.WebImage.deserializeBinaryFromReader);
      msg.addFullMatchingImages(value);
      break;
    case 3:
      var value = new proto.google.cloud.vision.v1.WebDetection.WebImage;
      reader.readMessage(value,proto.google.cloud.vision.v1.WebDetection.WebImage.deserializeBinaryFromReader);
      msg.addPartialMatchingImages(value);
      break;
    case 4:
      var value = new proto.google.cloud.vision.v1.WebDetection.WebPage;
      reader.readMessage(value,proto.google.cloud.vision.v1.WebDetection.WebPage.deserializeBinaryFromReader);
      msg.addPagesWithMatchingImages(value);
      break;
    case 6:
      var value = new proto.google.cloud.vision.v1.WebDetection.WebImage;
      reader.readMessage(value,proto.google.cloud.vision.v1.WebDetection.WebImage.deserializeBinaryFromReader);
      msg.addVisuallySimilarImages(value);
      break;
    case 8:
      var value = new proto.google.cloud.vision.v1.WebDetection.WebLabel;
      reader.readMessage(value,proto.google.cloud.vision.v1.WebDetection.WebLabel.deserializeBinaryFromReader);
      msg.addBestGuessLabels(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.WebDetection.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.WebDetection} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.WebDetection.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getWebEntitiesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      1,
      f,
      proto.google.cloud.vision.v1.WebDetection.WebEntity.serializeBinaryToWriter
    );
  }
  f = message.getFullMatchingImagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      2,
      f,
      proto.google.cloud.vision.v1.WebDetection.WebImage.serializeBinaryToWriter
    );
  }
  f = message.getPartialMatchingImagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      3,
      f,
      proto.google.cloud.vision.v1.WebDetection.WebImage.serializeBinaryToWriter
    );
  }
  f = message.getPagesWithMatchingImagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.google.cloud.vision.v1.WebDetection.WebPage.serializeBinaryToWriter
    );
  }
  f = message.getVisuallySimilarImagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      6,
      f,
      proto.google.cloud.vision.v1.WebDetection.WebImage.serializeBinaryToWriter
    );
  }
  f = message.getBestGuessLabelsList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      8,
      f,
      proto.google.cloud.vision.v1.WebDetection.WebLabel.serializeBinaryToWriter
    );
  }
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.WebDetection.WebEntity.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.WebDetection.WebEntity.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebEntity} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.WebDetection.WebEntity.toObject = function(includeInstance, msg) {
  var f, obj = {
    entityId: jspb.Message.getFieldWithDefault(msg, 1, ""),
    score: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    description: jspb.Message.getFieldWithDefault(msg, 3, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebEntity}
 */
proto.google.cloud.vision.v1.WebDetection.WebEntity.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.WebDetection.WebEntity;
  return proto.google.cloud.vision.v1.WebDetection.WebEntity.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebEntity} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebEntity}
 */
proto.google.cloud.vision.v1.WebDetection.WebEntity.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setEntityId(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setScore(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setDescription(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.WebDetection.WebEntity.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.WebDetection.WebEntity.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebEntity} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.WebDetection.WebEntity.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getEntityId();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getScore();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getDescription();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
};


/**
 * optional string entity_id = 1;
 * @return {string}
 */
proto.google.cloud.vision.v1.WebDetection.WebEntity.prototype.getEntityId = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebEntity} returns this
 */
proto.google.cloud.vision.v1.WebDetection.WebEntity.prototype.setEntityId = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float score = 2;
 * @return {number}
 */
proto.google.cloud.vision.v1.WebDetection.WebEntity.prototype.getScore = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebEntity} returns this
 */
proto.google.cloud.vision.v1.WebDetection.WebEntity.prototype.setScore = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional string description = 3;
 * @return {string}
 */
proto.google.cloud.vision.v1.WebDetection.WebEntity.prototype.getDescription = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebEntity} returns this
 */
proto.google.cloud.vision.v1.WebDetection.WebEntity.prototype.setDescription = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.WebDetection.WebImage.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.WebDetection.WebImage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebImage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.WebDetection.WebImage.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, ""),
    score: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebImage}
 */
proto.google.cloud.vision.v1.WebDetection.WebImage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.WebDetection.WebImage;
  return proto.google.cloud.vision.v1.WebDetection.WebImage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebImage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebImage}
 */
proto.google.cloud.vision.v1.WebDetection.WebImage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setScore(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.WebDetection.WebImage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.WebDetection.WebImage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebImage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.WebDetection.WebImage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getScore();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.google.cloud.vision.v1.WebDetection.WebImage.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebImage} returns this
 */
proto.google.cloud.vision.v1.WebDetection.WebImage.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float score = 2;
 * @return {number}
 */
proto.google.cloud.vision.v1.WebDetection.WebImage.prototype.getScore = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebImage} returns this
 */
proto.google.cloud.vision.v1.WebDetection.WebImage.prototype.setScore = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};



/**
 * List of repeated fields within this message type.
 * @private {!Array<number>}
 * @const
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.repeatedFields_ = [4,5];



if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.WebDetection.WebPage.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebPage} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.toObject = function(includeInstance, msg) {
  var f, obj = {
    url: jspb.Message.getFieldWithDefault(msg, 1, ""),
    score: jspb.Message.getFloatingPointFieldWithDefault(msg, 2, 0.0),
    pageTitle: jspb.Message.getFieldWithDefault(msg, 3, ""),
    fullMatchingImagesList: jspb.Message.toObjectList(msg.getFullMatchingImagesList(),
    proto.google.cloud.vision.v1.WebDetection.WebImage.toObject, includeInstance),
    partialMatchingImagesList: jspb.Message.toObjectList(msg.getPartialMatchingImagesList(),
    proto.google.cloud.vision.v1.WebDetection.WebImage.toObject, includeInstance)
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebPage}
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.WebDetection.WebPage;
  return proto.google.cloud.vision.v1.WebDetection.WebPage.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebPage} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebPage}
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setUrl(value);
      break;
    case 2:
      var value = /** @type {number} */ (reader.readFloat());
      msg.setScore(value);
      break;
    case 3:
      var value = /** @type {string} */ (reader.readString());
      msg.setPageTitle(value);
      break;
    case 4:
      var value = new proto.google.cloud.vision.v1.WebDetection.WebImage;
      reader.readMessage(value,proto.google.cloud.vision.v1.WebDetection.WebImage.deserializeBinaryFromReader);
      msg.addFullMatchingImages(value);
      break;
    case 5:
      var value = new proto.google.cloud.vision.v1.WebDetection.WebImage;
      reader.readMessage(value,proto.google.cloud.vision.v1.WebDetection.WebImage.deserializeBinaryFromReader);
      msg.addPartialMatchingImages(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.WebDetection.WebPage.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebPage} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getUrl();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getScore();
  if (f !== 0.0) {
    writer.writeFloat(
      2,
      f
    );
  }
  f = message.getPageTitle();
  if (f.length > 0) {
    writer.writeString(
      3,
      f
    );
  }
  f = message.getFullMatchingImagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      4,
      f,
      proto.google.cloud.vision.v1.WebDetection.WebImage.serializeBinaryToWriter
    );
  }
  f = message.getPartialMatchingImagesList();
  if (f.length > 0) {
    writer.writeRepeatedMessage(
      5,
      f,
      proto.google.cloud.vision.v1.WebDetection.WebImage.serializeBinaryToWriter
    );
  }
};


/**
 * optional string url = 1;
 * @return {string}
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.getUrl = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebPage} returns this
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.setUrl = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional float score = 2;
 * @return {number}
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.getScore = function() {
  return /** @type {number} */ (jspb.Message.getFloatingPointFieldWithDefault(this, 2, 0.0));
};


/**
 * @param {number} value
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebPage} returns this
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.setScore = function(value) {
  return jspb.Message.setProto3FloatField(this, 2, value);
};


/**
 * optional string page_title = 3;
 * @return {string}
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.getPageTitle = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 3, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebPage} returns this
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.setPageTitle = function(value) {
  return jspb.Message.setProto3StringField(this, 3, value);
};


/**
 * repeated WebImage full_matching_images = 4;
 * @return {!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>}
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.getFullMatchingImagesList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.WebDetection.WebImage, 4));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>} value
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebPage} returns this
*/
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.setFullMatchingImagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebImage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebImage}
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.addFullMatchingImages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.google.cloud.vision.v1.WebDetection.WebImage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebPage} returns this
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.clearFullMatchingImagesList = function() {
  return this.setFullMatchingImagesList([]);
};


/**
 * repeated WebImage partial_matching_images = 5;
 * @return {!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>}
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.getPartialMatchingImagesList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.WebDetection.WebImage, 5));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>} value
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebPage} returns this
*/
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.setPartialMatchingImagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 5, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebImage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebImage}
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.addPartialMatchingImages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 5, opt_value, proto.google.cloud.vision.v1.WebDetection.WebImage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebPage} returns this
 */
proto.google.cloud.vision.v1.WebDetection.WebPage.prototype.clearPartialMatchingImagesList = function() {
  return this.setPartialMatchingImagesList([]);
};





if (jspb.Message.GENERATE_TO_OBJECT) {
/**
 * Creates an object representation of this proto.
 * Field names that are reserved in JavaScript and will be renamed to pb_name.
 * Optional fields that are not set will be set to undefined.
 * To access a reserved field use, foo.pb_<name>, eg, foo.pb_default.
 * For the list of reserved names please see:
 *     net/proto2/compiler/js/internal/generator.cc#kKeyword.
 * @param {boolean=} opt_includeInstance Deprecated. whether to include the
 *     JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @return {!Object}
 */
proto.google.cloud.vision.v1.WebDetection.WebLabel.prototype.toObject = function(opt_includeInstance) {
  return proto.google.cloud.vision.v1.WebDetection.WebLabel.toObject(opt_includeInstance, this);
};


/**
 * Static version of the {@see toObject} method.
 * @param {boolean|undefined} includeInstance Deprecated. Whether to include
 *     the JSPB instance for transitional soy proto support:
 *     http://goto/soy-param-migration
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebLabel} msg The msg instance to transform.
 * @return {!Object}
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.WebDetection.WebLabel.toObject = function(includeInstance, msg) {
  var f, obj = {
    label: jspb.Message.getFieldWithDefault(msg, 1, ""),
    languageCode: jspb.Message.getFieldWithDefault(msg, 2, "")
  };

  if (includeInstance) {
    obj.$jspbMessageInstance = msg;
  }
  return obj;
};
}


/**
 * Deserializes binary data (in protobuf wire format).
 * @param {jspb.ByteSource} bytes The bytes to deserialize.
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebLabel}
 */
proto.google.cloud.vision.v1.WebDetection.WebLabel.deserializeBinary = function(bytes) {
  var reader = new jspb.BinaryReader(bytes);
  var msg = new proto.google.cloud.vision.v1.WebDetection.WebLabel;
  return proto.google.cloud.vision.v1.WebDetection.WebLabel.deserializeBinaryFromReader(msg, reader);
};


/**
 * Deserializes binary data (in protobuf wire format) from the
 * given reader into the given message object.
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebLabel} msg The message object to deserialize into.
 * @param {!jspb.BinaryReader} reader The BinaryReader to use.
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebLabel}
 */
proto.google.cloud.vision.v1.WebDetection.WebLabel.deserializeBinaryFromReader = function(msg, reader) {
  while (reader.nextField()) {
    if (reader.isEndGroup()) {
      break;
    }
    var field = reader.getFieldNumber();
    switch (field) {
    case 1:
      var value = /** @type {string} */ (reader.readString());
      msg.setLabel(value);
      break;
    case 2:
      var value = /** @type {string} */ (reader.readString());
      msg.setLanguageCode(value);
      break;
    default:
      reader.skipField();
      break;
    }
  }
  return msg;
};


/**
 * Serializes the message to binary data (in protobuf wire format).
 * @return {!Uint8Array}
 */
proto.google.cloud.vision.v1.WebDetection.WebLabel.prototype.serializeBinary = function() {
  var writer = new jspb.BinaryWriter();
  proto.google.cloud.vision.v1.WebDetection.WebLabel.serializeBinaryToWriter(this, writer);
  return writer.getResultBuffer();
};


/**
 * Serializes the given message to binary data (in protobuf wire
 * format), writing to the given BinaryWriter.
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebLabel} message
 * @param {!jspb.BinaryWriter} writer
 * @suppress {unusedLocalVariables} f is only used for nested messages
 */
proto.google.cloud.vision.v1.WebDetection.WebLabel.serializeBinaryToWriter = function(message, writer) {
  var f = undefined;
  f = message.getLabel();
  if (f.length > 0) {
    writer.writeString(
      1,
      f
    );
  }
  f = message.getLanguageCode();
  if (f.length > 0) {
    writer.writeString(
      2,
      f
    );
  }
};


/**
 * optional string label = 1;
 * @return {string}
 */
proto.google.cloud.vision.v1.WebDetection.WebLabel.prototype.getLabel = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 1, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebLabel} returns this
 */
proto.google.cloud.vision.v1.WebDetection.WebLabel.prototype.setLabel = function(value) {
  return jspb.Message.setProto3StringField(this, 1, value);
};


/**
 * optional string language_code = 2;
 * @return {string}
 */
proto.google.cloud.vision.v1.WebDetection.WebLabel.prototype.getLanguageCode = function() {
  return /** @type {string} */ (jspb.Message.getFieldWithDefault(this, 2, ""));
};


/**
 * @param {string} value
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebLabel} returns this
 */
proto.google.cloud.vision.v1.WebDetection.WebLabel.prototype.setLanguageCode = function(value) {
  return jspb.Message.setProto3StringField(this, 2, value);
};


/**
 * repeated WebEntity web_entities = 1;
 * @return {!Array<!proto.google.cloud.vision.v1.WebDetection.WebEntity>}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.getWebEntitiesList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.WebDetection.WebEntity>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.WebDetection.WebEntity, 1));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.WebDetection.WebEntity>} value
 * @return {!proto.google.cloud.vision.v1.WebDetection} returns this
*/
proto.google.cloud.vision.v1.WebDetection.prototype.setWebEntitiesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 1, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebEntity=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebEntity}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.addWebEntities = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 1, opt_value, proto.google.cloud.vision.v1.WebDetection.WebEntity, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.WebDetection} returns this
 */
proto.google.cloud.vision.v1.WebDetection.prototype.clearWebEntitiesList = function() {
  return this.setWebEntitiesList([]);
};


/**
 * repeated WebImage full_matching_images = 2;
 * @return {!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.getFullMatchingImagesList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.WebDetection.WebImage, 2));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>} value
 * @return {!proto.google.cloud.vision.v1.WebDetection} returns this
*/
proto.google.cloud.vision.v1.WebDetection.prototype.setFullMatchingImagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 2, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebImage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebImage}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.addFullMatchingImages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 2, opt_value, proto.google.cloud.vision.v1.WebDetection.WebImage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.WebDetection} returns this
 */
proto.google.cloud.vision.v1.WebDetection.prototype.clearFullMatchingImagesList = function() {
  return this.setFullMatchingImagesList([]);
};


/**
 * repeated WebImage partial_matching_images = 3;
 * @return {!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.getPartialMatchingImagesList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.WebDetection.WebImage, 3));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>} value
 * @return {!proto.google.cloud.vision.v1.WebDetection} returns this
*/
proto.google.cloud.vision.v1.WebDetection.prototype.setPartialMatchingImagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 3, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebImage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebImage}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.addPartialMatchingImages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 3, opt_value, proto.google.cloud.vision.v1.WebDetection.WebImage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.WebDetection} returns this
 */
proto.google.cloud.vision.v1.WebDetection.prototype.clearPartialMatchingImagesList = function() {
  return this.setPartialMatchingImagesList([]);
};


/**
 * repeated WebPage pages_with_matching_images = 4;
 * @return {!Array<!proto.google.cloud.vision.v1.WebDetection.WebPage>}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.getPagesWithMatchingImagesList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.WebDetection.WebPage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.WebDetection.WebPage, 4));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.WebDetection.WebPage>} value
 * @return {!proto.google.cloud.vision.v1.WebDetection} returns this
*/
proto.google.cloud.vision.v1.WebDetection.prototype.setPagesWithMatchingImagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 4, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebPage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebPage}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.addPagesWithMatchingImages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 4, opt_value, proto.google.cloud.vision.v1.WebDetection.WebPage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.WebDetection} returns this
 */
proto.google.cloud.vision.v1.WebDetection.prototype.clearPagesWithMatchingImagesList = function() {
  return this.setPagesWithMatchingImagesList([]);
};


/**
 * repeated WebImage visually_similar_images = 6;
 * @return {!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.getVisuallySimilarImagesList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.WebDetection.WebImage, 6));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.WebDetection.WebImage>} value
 * @return {!proto.google.cloud.vision.v1.WebDetection} returns this
*/
proto.google.cloud.vision.v1.WebDetection.prototype.setVisuallySimilarImagesList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 6, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebImage=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebImage}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.addVisuallySimilarImages = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 6, opt_value, proto.google.cloud.vision.v1.WebDetection.WebImage, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.WebDetection} returns this
 */
proto.google.cloud.vision.v1.WebDetection.prototype.clearVisuallySimilarImagesList = function() {
  return this.setVisuallySimilarImagesList([]);
};


/**
 * repeated WebLabel best_guess_labels = 8;
 * @return {!Array<!proto.google.cloud.vision.v1.WebDetection.WebLabel>}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.getBestGuessLabelsList = function() {
  return /** @type{!Array<!proto.google.cloud.vision.v1.WebDetection.WebLabel>} */ (
    jspb.Message.getRepeatedWrapperField(this, proto.google.cloud.vision.v1.WebDetection.WebLabel, 8));
};


/**
 * @param {!Array<!proto.google.cloud.vision.v1.WebDetection.WebLabel>} value
 * @return {!proto.google.cloud.vision.v1.WebDetection} returns this
*/
proto.google.cloud.vision.v1.WebDetection.prototype.setBestGuessLabelsList = function(value) {
  return jspb.Message.setRepeatedWrapperField(this, 8, value);
};


/**
 * @param {!proto.google.cloud.vision.v1.WebDetection.WebLabel=} opt_value
 * @param {number=} opt_index
 * @return {!proto.google.cloud.vision.v1.WebDetection.WebLabel}
 */
proto.google.cloud.vision.v1.WebDetection.prototype.addBestGuessLabels = function(opt_value, opt_index) {
  return jspb.Message.addToRepeatedWrapperField(this, 8, opt_value, proto.google.cloud.vision.v1.WebDetection.WebLabel, opt_index);
};


/**
 * Clears the list making it empty but non-null.
 * @return {!proto.google.cloud.vision.v1.WebDetection} returns this
 */
proto.google.cloud.vision.v1.WebDetection.prototype.clearBestGuessLabelsList = function() {
  return this.setBestGuessLabelsList([]);
};


goog.object.extend(exports, proto.google.cloud.vision.v1);
