export enum DialogType {
  AcceptableUse = 'acceptableUse',
  AcceptMatch = 'acceptMatch',
  Account = 'account',
  Changelog = 'changelog',
  Channel = 'channel',
  Download = 'download',
  MapDetails = 'mapDetails',
  MapPreview = 'mapPreview',
  PartyInvite = 'partyInvite',
  PrivacyPolicy = 'privacyPolicy',
  Settings = 'settings',
  Simple = 'simple',
  ShieldBatteryHealth = 'shieldBatteryHealth',
  StarcraftHealth = 'starcraftHealth',
  StarcraftPath = 'starcraftPath',
  TermsOfService = 'termsOfService',
  UpdateAvailable = 'updateAvailable',
  Whispers = 'whispers',
  ExternalLink = 'externalLink',
}
