export enum NotificationType {
  EmailVerification = 'emailVerification',
  PartyInvite = 'partyInvite',
}

export interface BaseNotification {
  /**
   * A string that is unique if the notification is unique. For locally-generated notifications
   * that should never show duplicates, this might be a constant string. For server-generated ones
   * that have multiple of the same type (e.g. chat notifications, party invites, etc.) these are
   * generated by the server.
   */
  readonly id: string
  readonly type: NotificationType
  readonly read: boolean
  readonly createdAt: number
  /** A flag indicating whether the notification is generated locally or on the server. */
  readonly local?: boolean
}

export interface EmailVerificationNotification extends BaseNotification {
  type: typeof NotificationType.EmailVerification
}

export const EMAIL_VERIFICATION_ID = 'local-emailVerification'

export interface PartyInviteNotification extends BaseNotification {
  type: typeof NotificationType.PartyInvite
  from: string
  partyId: string
}

export type Notification = EmailVerificationNotification | PartyInviteNotification

export interface NotificationServerInitEvent {
  type: 'serverInit'
  notifications: Notification[]
}

export interface NotificationAddEvent {
  type: 'add'
  notification: Notification
}

export interface NotificationClearByIdEvent {
  type: 'clearById'
  notificationId: string
}

export type NotificationEvent =
  | NotificationServerInitEvent
  | NotificationAddEvent
  | NotificationClearByIdEvent

export interface MarkNotificationsReadServerBody {
  notificationIds: string[]
}
