/*
 Generated by typeshare 1.13.4
*/

export enum RestrictedNameReason {
  Profanity = 'profanity',
  Reserved = 'reserved',
}

export interface CheckAllowedNameResponse {
  allowed: boolean
  reason?: RestrictedNameReason
}

/**
 * All of the matchmaking types that we support. These values match the enum values used in the
 * database.
 */
export enum MatchmakingType {
  Match1v1 = '1v1',
  Match1v1Fastest = '1v1fastest',
  Match2v2 = '2v2',
  Match2v2Bgh = '2v2bgh',
  Match2v2Hunters = '2v2hunters',
  Match2v2Fastest = '2v2fastest',
  Match3v3Bgh = '3v3bgh',
  Match3v3Hunters = '3v3hunters',
  Match3v3Fastest = '3v3fastest',
}

/** A single player's entry in a match found message. */
export interface MatchedPlayer {
  id: TypeshareTypes.SbUserId
  /**
   * Base64-encoded JSON QueueTicket. Node.js stores this and sends it back
   * via POST /matchmaker/requeue if the match fails to start.
   */
  ticket: string
}

/** Data carried by the [`PublishedMatchmakingMessage::MatchFound`] event. */
export interface MatchFoundMessage {
  mode: MatchmakingType
  teamA: MatchedPlayer[]
  teamB: MatchedPlayer[]
  /** Overall match-quality score (in seconds of wait) the match formed at. */
  quality: number
  /** Variance of the matched players' effective ratings (raw skill-spread input to `quality`). */
  skillVariance: number
  /** Win probability of team A vs team B (0.5 == perfectly balanced). */
  winProbability: number
  /** Effective team ratings used to compute `win_probability`. */
  teamARating: number
  teamBRating: number
  /**
   * Estimated one-way latency (ms) of the match's worst pairwise link, computed from the
   * players' rally-point server pings (raw latency input to `quality`).
   */
  maxLatency: number
}

export interface SbPermissions {
  editPermissions: boolean
  debug: boolean
  banUsers: boolean
  manageLeagues: boolean
  manageMaps: boolean
  manageMapPools: boolean
  manageMatchmaking: boolean
  manageMatchmakingSeasons: boolean
  manageMatchmakingTimes: boolean
  manageRallyPointServers: boolean
  massDeleteMaps: boolean
  moderateChatChannels: boolean
  manageNews: boolean
  manageBugReports: boolean
  manageGameReports: boolean
  manageRestrictedNames: boolean
  manageSignupCodes: boolean
}

export interface UrgentMessage {
  id: string
  title: string
  message: string
  /** The time the message was published (in UTC). This will serialize as an RFC 3339 string. */
  publishedAt: string
}

/** The privacy level for a map. This determines who can use the map for creating games. */
export enum MapVisibility {
  Private = 'PRIVATE',
  Public = 'PUBLIC',
  Official = 'OFFICIAL',
}

/**
 * Messages published to Node (via Redis pub/sub) about game-report events. Node turns these into
 * user-facing notifications (and later shares the same channel with the Discord webhook). This is
 * deliberately kept as pub/sub rather than a direct write so the notification/webhook machinery
 * stays in Node, where the rest of it lives.
 */
export type PublishedGameReportMessage =
  /**
   * A report was resolved as `Actioned`. The listed users — the actioned report's reporter plus
   * the reporters of any sibling reports (same game + target) that were resolved as `Duplicate` —
   * should be told that a player they reported was punished. Content stays deliberately vague on
   * the Node side (no names, no game link) as an anti-retaliation measure.
   */
  {
    type: 'reportActioned'
    data: {
      reporterIds: TypeshareTypes.SbUserId[]
    }
  }

/** Messages published to the Redis `"matchmaking"` channel. */
export type PublishedMatchmakingMessage = { type: 'matchFound'; data: MatchFoundMessage }

export type PublishedMessage =
  | { type: 'news'; data: PublishedNewsMessage }
  | { type: 'user'; data: PublishedUserMessage }
  | { type: 'matchmaking'; data: PublishedMatchmakingMessage }
  | { type: 'gameReport'; data: PublishedGameReportMessage }

export type PublishedNewsMessage = { type: 'urgentMessageChanged'; data: undefined }

export type PublishedUserMessage =
  | {
      type: 'permissionsChanged'
      data: {
        userId: TypeshareTypes.SbUserId
        permissions: SbPermissions
      }
    }
  | {
      type: 'emailChanged'
      data: {
        userId: TypeshareTypes.SbUserId
        email: string
      }
    }

/**
 * Error codes the matchmaking HTTP API returns in the `code` field of its JSON error bodies. This
 * is the single source of truth for the set of codes; it's shared with the Node.js client via
 * typeshare so both sides agree on the exact strings (rather than the client re-declaring them).
 */
export enum RsMatchmakerErrorCode {
  /** The player is already in the queue. */
  AlreadyInQueue = 'alreadyInQueue',
  /** The queue request listed no modes to search for. */
  NoModesSelected = 'noModesSelected',
  /** The player was not found in the queue (e.g. cancel/requeue for someone already removed). */
  NotFound = 'notFound',
  /** A requeue ticket was malformed and couldn't be decoded. */
  InvalidTicket = 'invalidTicket',
  /** A requeue ticket was issued by a previous process — server-rs has restarted since. */
  StaleTicket = 'staleTicket',
}
