/*
 Generated by typeshare 1.13.2
*/

export enum RestrictedNameReason {
  Profanity = 'profanity',
  Reserved = 'reserved',
}

export interface CheckAllowedNameResponse {
  allowed: boolean
  reason?: RestrictedNameReason
}

export interface SbPermissions {
  editPermissions: boolean
  debug: boolean
  banUsers: boolean
  manageLeagues: boolean
  manageMaps: boolean
  manageMapPools: boolean
  manageMatchmakingSeasons: boolean
  manageMatchmakingTimes: boolean
  manageRallyPointServers: boolean
  massDeleteMaps: boolean
  moderateChatChannels: boolean
  manageNews: boolean
  manageBugReports: boolean
  manageRestrictedNames: boolean
}

export type PublishedMessage = { type: 'user'; data: PublishedUserMessage }

export type PublishedUserMessage = {
  type: 'permissionsChanged'
  data: {
    userId: number
    permissions: SbPermissions
  }
}
