/*
 Generated by typeshare 1.13.2
*/

export enum RestrictedNameReason {
  Profanity = 'profanity',
  Reserved = 'reserved',
}

export interface CheckAllowedNameResponse {
  allowed: boolean
  reason?: RestrictedNameReason
}

export interface SbPermissions {
  editPermissions: boolean
  debug: boolean
  banUsers: boolean
  manageLeagues: boolean
  manageMaps: boolean
  manageMapPools: boolean
  manageMatchmakingSeasons: boolean
  manageMatchmakingTimes: boolean
  manageRallyPointServers: boolean
  massDeleteMaps: boolean
  moderateChatChannels: boolean
  manageNews: boolean
  manageBugReports: boolean
  manageRestrictedNames: boolean
}

export interface UrgentMessage {
  title: string
  message: string
  /** The time the message was published (in UTC). This will serialize as an RFC 3339 string. */
  publishedAt: string
}

export type PublishedMessage =
  | { type: 'news'; data: PublishedNewsMessage }
  | { type: 'user'; data: PublishedUserMessage }

export type PublishedNewsMessage = { type: 'urgentMessageChanged'; data: undefined }

export type PublishedUserMessage = {
  type: 'permissionsChanged'
  data: {
    userId: number
    permissions: SbPermissions
  }
}
