import { useState } from 'react'
import { useTranslation } from 'react-i18next'
import styled from 'styled-components'
import { ALL_TILESET_IDS, TILESET_PLACEHOLDER_COLORS, TilesetId } from '../../../common/maps'
import { MaterialIcon } from '../../icons/material/material-icon'
import { buttonReset } from '../../material/button-reset'
import { MenuItem } from '../../material/menu/item'
import { MenuList } from '../../material/menu/menu'
import { Popover, usePopoverController, useRefAnchorPosition } from '../../material/popover'
import { makePublicAssetUrl } from '../../network/server-url'
import { bodySmall, labelSmall, singleLine } from '../../styles/typography'

export type { TilesetId }

/** Untranslated on purpose: these name a StarCraft tileset, not general UI copy. */
const TILESET_LABELS: Readonly<Record<TilesetId, string>> = {
  jungle: 'Jungle',
  badlands: 'Badlands',
  desert: 'Desert',
  ice: 'Ice',
  space: 'Space',
  twilight: 'Twilight',
  ashworld: 'Ashworld',
}

export const DEFAULT_TILESET: TilesetId = 'jungle'

/**
 * URL for a tileset's rendered minimap preview, generated by `tools/gen-minimap-previews.ts` and
 * served as a static asset (see `server/public/images/minimaps`, matching how e.g.
 * `server/public/images/ranks` is served and consumed elsewhere via `makePublicAssetUrl`).
 */
function getMinimapImageUrl(tileset: TilesetId): string {
  return makePublicAssetUrl(`images/minimaps/${tileset}.png`)
}

// Percentage (x, y) positions for each of the 8 preview rows' minimap dots.
const TEAM_DOT_POSITIONS: ReadonlyArray<readonly [number, number]> = [
  [16, 76],
  [26, 86],
  [12, 62],
  [30, 70],
  [76, 18],
  [86, 28],
  [66, 12],
  [72, 30],
]
const FFA_DOT_POSITIONS: ReadonlyArray<readonly [number, number]> = [
  [14, 14],
  [50, 9],
  [84, 14],
  [87, 50],
  [84, 84],
  [50, 87],
  [14, 84],
  [11, 50],
]

const Header = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
  margin-bottom: 8px;
`

const HeaderLabel = styled.div`
  ${labelSmall};
  flex-grow: 1;
  text-transform: uppercase;
  color: var(--theme-on-surface-variant);
`

const TilesetTrigger = styled.button`
  ${buttonReset};
  flex-shrink: 0;
  display: flex;
  align-items: center;
  gap: 2px;

  color: var(--theme-on-surface-variant);
  cursor: pointer;
  transition: color 100ms linear;

  &:hover,
  &:focus-visible {
    color: var(--color-blue80);
  }

  &:focus-visible {
    outline: 2px solid var(--theme-amber);
    outline-offset: 2px;
  }
`

const TilesetTriggerLabel = styled.span`
  ${labelSmall};
  letter-spacing: 0.4px;
`

const TilesetMenuList = styled(MenuList)`
  width: 140px;
`

const SelectedTilesetIcon = styled(MaterialIcon)`
  color: var(--theme-amber);
`

function TilesetSelector({
  value,
  onChange,
}: {
  value: TilesetId
  onChange: (id: TilesetId) => void
}) {
  const [anchorRef, anchorX, anchorY, refreshAnchorPos] = useRefAnchorPosition<HTMLButtonElement>(
    'right',
    'bottom',
  )
  const [open, openPopover, closePopover] = usePopoverController({ refreshAnchorPos })

  return (
    <>
      <TilesetTrigger
        ref={anchorRef}
        type='button'
        onClick={event => (open ? closePopover() : openPopover(event))}>
        <TilesetTriggerLabel>{TILESET_LABELS[value]}</TilesetTriggerLabel>
        <MaterialIcon icon='arrow_drop_down' size={16} />
      </TilesetTrigger>
      <Popover
        open={open}
        onDismiss={closePopover}
        anchorX={anchorX ?? 0}
        anchorY={anchorY ?? 0}
        originX='right'
        originY='top'>
        <TilesetMenuList dense={true}>
          {ALL_TILESET_IDS.map(id => (
            <MenuItem
              key={id}
              text={TILESET_LABELS[id]}
              dense={true}
              trailingContent={id === value ? <SelectedTilesetIcon icon='check' size={14} /> : null}
              onClick={() => {
                onChange(id)
                closePopover()
              }}
            />
          ))}
        </TilesetMenuList>
      </Popover>
    </>
  )
}

// Square, matching a real minimap's aspect ratio: `Preview` (team-color-settings.tsx) fixes this
// panel's width at 288px, and letting height follow via aspect-ratio (rather than the old fixed
// 180px) avoids ever cropping or distorting the rendered map image.
const Minimap = styled.div<{ $background: string }>`
  position: relative;
  width: 100%;
  aspect-ratio: 1 / 1;
  margin-bottom: 12px;
  overflow: hidden;

  border: 1px solid rgb(255 255 255 / 0.1);
  background-color: ${props => props.$background};
`

// `object-fit: cover`: a non-square map fills the square box (cropping its edges) rather than
// letterboxing against the fallback color -- the preview only needs to convey the tileset's look,
// not the whole map, and filling the box reads cleaner.
const MinimapImage = styled.img`
  position: absolute;
  inset: 0;
  width: 100%;
  height: 100%;
  object-fit: cover;
`

const Dot = styled.div<{ $color: string; $x: number; $y: number }>`
  position: absolute;
  left: ${props => props.$x}%;
  top: ${props => props.$y}%;
  width: 9px;
  height: 9px;
  background-color: ${props => props.$color};
  outline: 1px solid rgb(0 0 0 / 0.55);
`

const Roster = styled.div`
  display: flex;
  gap: 16px;
`

const RosterColumn = styled.div`
  flex: 1;
  min-width: 0;
  display: flex;
  flex-direction: column;
  gap: 5px;
`

const RosterRow = styled.div`
  display: flex;
  align-items: center;
  gap: 8px;
`

const RosterSwatch = styled.div<{ $color: string }>`
  width: 10px;
  height: 10px;
  flex-shrink: 0;
  background-color: ${props => props.$color};
  box-shadow: inset 0 0 0 1px rgb(0 0 0 / 0.5);
`

const RosterName = styled.div<{ $isSelf: boolean }>`
  ${bodySmall};
  ${singleLine};
  color: ${props => (props.$isSelf ? 'var(--color-grey99)' : 'var(--color-grey-blue80)')};
`

export interface PreviewRow {
  color: string
  name: string
  isSelf: boolean
}

export interface TeamColorPreviewProps {
  /** Which mock scenario this preview illustrates (changes the header text and dot layout). */
  variant: 'team' | 'ffa'
  /** Exactly 8 rows, in minimap-dot order; the first 4 render in the left roster column. */
  rows: ReadonlyArray<PreviewRow>
  tileset: TilesetId
  onTilesetChange: (id: TilesetId) => void
  className?: string
}

/**
 * A mock minimap + roster preview of the currently active color assignment, shared by the team
 * and individual-colors cards (with different mock rosters/dot layouts per `variant`).
 */
export function TeamColorPreview({
  variant,
  rows,
  tileset,
  onTilesetChange,
  className,
}: TeamColorPreviewProps) {
  const { t } = useTranslation()
  const dotPositions = variant === 'team' ? TEAM_DOT_POSITIONS : FFA_DOT_POSITIONS
  const headerLabel =
    variant === 'team'
      ? t('settings.game.gameplay.teamColors.previewHeaderTeam', 'Preview (4v4)')
      : t('settings.game.gameplay.teamColors.previewHeaderFfa', 'Preview (no teams)')
  // Tracks the tileset (if any) whose image failed to load, so switching tilesets always retries
  // loading rather than getting stuck on a stale failure.
  const [erroredTileset, setErroredTileset] = useState<TilesetId | null>(null)

  return (
    <div className={className}>
      <Header>
        <HeaderLabel>{headerLabel}</HeaderLabel>
        <TilesetSelector value={tileset} onChange={onTilesetChange} />
      </Header>
      <Minimap $background={TILESET_PLACEHOLDER_COLORS[tileset]}>
        {erroredTileset !== tileset ? (
          <MinimapImage
            key={tileset}
            src={getMinimapImageUrl(tileset)}
            alt=''
            draggable='false'
            onError={() => setErroredTileset(tileset)}
          />
        ) : null}
        {rows.map((row, index) => {
          const [x, y] = dotPositions[index]
          return <Dot key={index} $color={row.color} $x={x} $y={y} />
        })}
      </Minimap>
      <Roster>
        <RosterColumn>
          {rows.slice(0, 4).map((row, index) => (
            <RosterRow key={index}>
              <RosterSwatch $color={row.color} />
              <RosterName $isSelf={row.isSelf}>{row.name}</RosterName>
            </RosterRow>
          ))}
        </RosterColumn>
        <RosterColumn>
          {rows.slice(4).map((row, index) => (
            <RosterRow key={index}>
              <RosterSwatch $color={row.color} />
              <RosterName $isSelf={row.isSelf}>{row.name}</RosterName>
            </RosterRow>
          ))}
        </RosterColumn>
      </Roster>
    </div>
  )
}
