name: Build Base Images

on:
  workflow_dispatch:
  schedule:
    # Rebuild base images weekly on Sundays at 2 AM UTC
    - cron: '0 2 * * 0'

jobs:
  build-base-images:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      packages: write
    
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Log in to the Container registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Build and push sqlx-cli base image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.base
          target: sqlx-runtime
          push: true
          tags: |
            ghcr.io/${{ github.repository }}/base:sqlx-tools
            ghcr.io/${{ github.repository }}/base:sqlx-tools-${{ github.run_number }}
          cache-from: type=gha
          cache-to: type=gha,mode=max